services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: math_agent_postgres
    environment:
      POSTGRES_USER: mathagent
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mathagent_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mathagent -d mathagent_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Qdrant Vector Database - NO HEALTH CHECK
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: math_agent_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    restart: unless-stopped

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: math_agent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
  qdrant_data:
    driver: local
  redis_data:
    driver: local